INDICATORS = [
    "sma", "ema", "dema", "tema", "trima", "kama", "mama", "mavp",
    "midpoint", "midprice", "sar", "sarext", "t3", "wma", "bbands",
    "adx", "adxr", "apo", "aroon", "aroonosc", "bop", "cci", "cmo",
    "dx", "macd", "macdext", "macdfix", "mfi", "minus_di", "minus_dm",
    "mom", "plus_di", "plus_dm", "ppo", "roc", "rocp", "rocr", "rocr100",
    "rsi", "stoch", "stochf", "stochrsi", "trix", "ultosc", "willr",
    "ad", "adosc", "obv", "atr", "natr", "trange", "avgprice", "medprice",
    "typprice", "wclprice", "ht_dcperiod", "ht_dcphase", "ht_phasor",
    "ht_sine", "ht_trendmode", "cdl2crows", "cdl3blackcrows", "cdl3inside",
    "cdl3linestrike", "cdl3outside", "cdl3starsinsouth", "cdl3whitesoldiers",
    "cdlabandonedbaby", "cdladvanceblock", "cdlbelthold", "cdlbreakaway",
    "cdlclosingmarubozu", "cdlconcealbabyswall", "cdlcounterattack",
    "cdldarkcloudcover", "cdldoji", "cdldojistar", "cdldragonflydoji",
    "cdlengulfing", "cdleveningdojistar", "cdleveningstar", "cdlgapsidesidewhite",
    "cdlgravestonedoji", "cdlhammer", "cdlhangingman", "cdlharami", "cdlharamicross",
    "cdlhighwave", "cdlhikkake", "cdlhikkakemod", "cdlidentical3crows", "cdlinneck",
    "cdlinvertedhammer", "cdlkicking", "cdlkickingbylength", "cdlladderbottom",
    "cdllongleggeddoji", "cdllongline", "cdlmarubozu", "cdlmatchinglow", "cdlonneck",
    "cdlpiercing", "cdlrickshawman", "cdlrisefall3methods", "cdlseparatinglines",
    "cdlshootingstar", "cdlshortline", "cdlspinningtop", "cdlstalledpattern",
    "cdlsticksandwich", "cdltakuri", "cdltasukigap", "cdlthrusting", "cdltristar",
    "cdlunique3river", "cdlupsidegap2crows", "cdlxsidegap3methods"
]